services:
  student01:
    build: ./services/student01
    container_name: student01
    ports:
      - "8101:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 5s
      timeout: 2s
      retries: 5
  student02:
    build: ./services/student02
    container_name: student02
    ports:
      - "8102:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8102/health"]
      interval: 5s
      timeout: 2s
      retries: 5
  student03:
    build: ./services/student03
    container_name: student03
    ports:
      - "8103:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 5s
      timeout: 2s
      retries: 5
  student04:
    build: ./services/student04
    container_name: student04
    ports:
      - "8104:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 5s
      timeout: 2s
      retries: 5
  student06:
    build: ./services/student06
    container_name: student06
    ports:
      - "8106:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 5s
      timeout: 2s
      retries: 5
  student07:
    build: ./services/student07
    container_name: student07
    ports:
      - "8107:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 5s
      timeout: 2s
      retries: 5